[[tree_sitter_julia]]
arch = "aarch64"
git-tree-sha1 = "a6b30b423804625b68e55a4454557a4c5d68e973"
os = "macos"

    [[tree_sitter_julia.download]]
    sha256 = "88f6bde766dce8a4a0373b41d775c06536936bed4815f230ec945ae558982afb"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.aarch64-apple-darwin.tar.gz"
[[tree_sitter_julia]]
arch = "aarch64"
git-tree-sha1 = "fda3cf3dc2100c89f6ddada9073cc33756e681e2"
libc = "glibc"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "1b2f28922c8dd6ff761000a8300ee8ec79f81883036519d5a445696fba910647"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.aarch64-linux-gnu.tar.gz"
[[tree_sitter_julia]]
arch = "aarch64"
git-tree-sha1 = "5e52c21eac15ef3034702855008bd25c82e0f7d5"
libc = "musl"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "e2794a3f296a06fed7ac10453a5dc8e31571e0550d416df380317d1db4783e92"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.aarch64-linux-musl.tar.gz"
[[tree_sitter_julia]]
arch = "aarch64"
git-tree-sha1 = "b997cdefce5d2d1801de5f23103c0e04517945bd"
os = "freebsd"

    [[tree_sitter_julia.download]]
    sha256 = "a37dde93cf7ddcb430e6871eab70988631beabd2ef140ff57af358394a1b8ac3"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.aarch64-unknown-freebsd.tar.gz"
[[tree_sitter_julia]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "780aa796ac9a456fd55c3582e882be40ad1dbe75"
libc = "glibc"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "a52d318a5086024887b6b0580a60c8921ecb7e0bf2c568c6c5ee206dd357e5ff"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.armv6l-linux-gnueabihf.tar.gz"
[[tree_sitter_julia]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4462aefcfbbc3824a97e0ded403074ee6dabeaf9"
libc = "musl"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "8550e15abc64ab96d52b0d011c4b59d133af4e1c056933c9f53d194bb4d7f08b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.armv6l-linux-musleabihf.tar.gz"
[[tree_sitter_julia]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "909f047066ad8b7fe8070552536f4bbe553daae8"
libc = "glibc"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "91cb862fbb892f4d1035c92fb49a30da081e0690030476b478103e03930440f6"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.armv7l-linux-gnueabihf.tar.gz"
[[tree_sitter_julia]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f34df41f8aa0b6c4df65a09ef701a6ce489f8fcd"
libc = "musl"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "3c4f0e263b439aaac22050caa799cce4c99960c0cad4e54e0a664262f8c74fd3"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.armv7l-linux-musleabihf.tar.gz"
[[tree_sitter_julia]]
arch = "i686"
git-tree-sha1 = "0ded56788d35d1c931bde0ace8e7b5888789b3d6"
libc = "glibc"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "d3a3e4f0f2e5ed8efe8cf070ab784c82a400d0ec13c3df1d32c75eee0f0a24fd"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.i686-linux-gnu.tar.gz"
[[tree_sitter_julia]]
arch = "i686"
git-tree-sha1 = "7715c007498127a777e68a6687eca7d9090e6d7a"
libc = "musl"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "ee30445ee606ddc916439e9afa70bd5eba774cc5b03a4fee177610145701b200"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.i686-linux-musl.tar.gz"
[[tree_sitter_julia]]
arch = "i686"
git-tree-sha1 = "d925463ca511d346bbda1474ddc0ecab7ffcd76e"
os = "windows"

    [[tree_sitter_julia.download]]
    sha256 = "99301804fe6d44a3939f38baf88e95aada2198de50ae0a2c9c6d7651b4f86981"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.i686-w64-mingw32.tar.gz"
[[tree_sitter_julia]]
arch = "powerpc64le"
git-tree-sha1 = "f5b42b13087f16da63143ebbbdb37f3c23268fdf"
libc = "glibc"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "9fc8ce02e562e0315bd99d0a466748f152b6a2ecc981f15e432ae7986d828682"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.powerpc64le-linux-gnu.tar.gz"
[[tree_sitter_julia]]
arch = "riscv64"
git-tree-sha1 = "690e0fd637753d99818407711a85a4693235610e"
libc = "glibc"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "88e9ba3253cfed47e953c576b20af6a7be408a2ad4112b13c7dadb251f8e2459"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.riscv64-linux-gnu.tar.gz"
[[tree_sitter_julia]]
arch = "x86_64"
git-tree-sha1 = "d977e58673f0f8530632d6f484fe92ee639b3037"
os = "macos"

    [[tree_sitter_julia.download]]
    sha256 = "285bcb6960b1c0a8645aec65e739cbb10249b318a7238fb4d757ac2a0b24a53a"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.x86_64-apple-darwin.tar.gz"
[[tree_sitter_julia]]
arch = "x86_64"
git-tree-sha1 = "b9b1848b03d3a2bc5a3db45a3f35b26256cd75e9"
libc = "glibc"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "b8ef1e45b7675b133786675b3fb30cc62e2e6c143452706cd1e876918429c73b"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.x86_64-linux-gnu.tar.gz"
[[tree_sitter_julia]]
arch = "x86_64"
git-tree-sha1 = "451be3663869d9f0a06cea7e34fe87d804162540"
libc = "musl"
os = "linux"

    [[tree_sitter_julia.download]]
    sha256 = "6dacb870a686d4be198c859f57abdea9dafa342f52f68f19e630cf715ae95365"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.x86_64-linux-musl.tar.gz"
[[tree_sitter_julia]]
arch = "x86_64"
git-tree-sha1 = "81770287b873d396b52f69e8e4cb09c943f8bb58"
os = "freebsd"

    [[tree_sitter_julia.download]]
    sha256 = "e25b427f3c2af3f437fb080293273c17840114427822446c8d97e40e64fcbb19"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.x86_64-unknown-freebsd.tar.gz"
[[tree_sitter_julia]]
arch = "x86_64"
git-tree-sha1 = "db735fa16906357e4e570371df04dc866e85e17c"
os = "windows"

    [[tree_sitter_julia.download]]
    sha256 = "fa12926c331b1186b3846d7878821da369ad7df6d505402bad64780a1e36b48a"
    url = "https://github.com/JuliaBinaryWrappers/tree_sitter_julia_jll.jl/releases/download/tree_sitter_julia-v0.25.0+0/tree_sitter_julia.v0.25.0.x86_64-w64-mingw32.tar.gz"
